### ISSUE TITLE
SEPTA: mdb_source_id 502 & 503 re-direct to the same url[BUG]

### ISSUE THREAD

**Issue by praneethd7** [MobilityData/mobility-database-catalogs#201]
**Describe the bug**
The `mdb_source_id` 502 & 503 for SEPTA bus and rail redirect to the same URL despite having a different URL in the database catalogs. Also, the downloaded file from both URLs is `gtfs_public`, which has the `google_bus.zip` and `google_rail.zip` in it. 

https://github.com/septadev/GTFS/releases/download/v202106061/gtfs_public.zip#google_bus.zip
https://github.com/septadev/GTFS/releases/download/v202106061/gtfs_public.zip#google_rail.zip

**To Reproduce**
1. Go to 'catalogs csv'
2. Scroll down to `mdb_source_id` 502 & 503
4. Click either urls

**Expected behavior**
Ideally, the URL for the bus and rail should be different and should download their respective gtfs `. zip` file

**Comment by praneethd7** [comment]
A bit of digging led me to this [#issue](https://github.com/septadev/GTFS/issues/19) posted on septadev github repo. According to this, there are separate links for bus and rail:

https://www3.septa.org/developer/google_bus.zip
https://www3.septa.org/developer/google_rail.zip

 However, I am not sure how frequently they are updated.

**Comment by emmambd** [comment]
Thank you for doing some detective work and finding these @praneethd7 ! These both look more up to date than the URLs currently provided in the CSV so we should add them. 

@maximearmstrong I've tried to update these on 2 different days and keep getting the SSL certificate error: 

`requests.exceptions.RequestException: FAILURE! Exception HTTPSConnectionPool(host='www3.septa.org', port=443): Max retries exceeded with url: /developer/google_bus.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))) occurred when downloading URL https://www3.septa.org/developer/google_bus.zip.`

Is there anything we can do on our side or ask SEPTA?
