### ISSUE TITLE
[BUG] Feed IDs 481 and 1156 are identical

### ISSUE THREAD

**Issue by wklumpen** [MobilityData/mobility-database-catalogs#297]
Both feeds are from Potomac and Rappahannock Transportation Commission (PRTC), but they seem to live under different URLS. They are the same feed though, down to the size of each file and the modification dates.

Merging into 481 would keep the one under the PRTC website name, but Merging into 1156 would match the URL with the branding.

I have no idea which one is more stable.

![Screenshot from 2023-09-12 11-28-07](https://github.com/MobilityData/mobility-database-catalogs/assets/7478016/fb8614b6-4b16-49bf-bfd3-ea704b1ecab2)

What's the best way forward for this? Do I need to open a PR of some kind?

**Comment by emmambd** [comment]
@wklumpen We aim to use the GTFS URL that's advertised by the agency on their website, so 1156 would be the preferred URL: https://omniride.com/about/tools/ since http://www.prtctransit.org now redirects to https://omniride.com/.

The steps here would be to set the status of 481 to `deprecated`. We'll add a redirect to `1156` once https://github.com/MobilityData/mobility-database-catalogs/issues/131 is added.
