### ISSUE TITLE
Update source ID to be numerical

### ISSUE THREAD

**Issue by emmambd** [MobilityData/mobility-database-catalogs#51]
**How do we know when this done?**

- Sources have generated numerical ID
- JSON file names are country-code-subdivision-code-provider-numerical-id.json

**Comment by maximearmstrong** [comment]
A few things to consider with this modification:
1. It will be easier for user to experience collisions when opening a PR. Use case: User 1 opens a PR in the morning, but is asked to make changes before the merge. User 2 opens a PR in the afternoon and it passes all the tests, so we merge. User 1's source ID could now be invalid, since every `mdb_source_id` must be unique and incremental. User 1 would have to delete its source locally, generate and push it again.
2. Deleting the sources will not be an option if we want the IDs to go from 1 to N and be truly incremental. This is necessary if we eventually use the IDs in a SQL database. Deprecating or modifying the sources will be the way to go.
3. To make sense in a SQL database, the IDs must be attributed per catalog, and not per sub catalog, ie. source 1 could be a GTFS source, source 2 a GTFS-RT source, source 3 a GBFS source, and so on. 
The `source` table would contain the columns for the features shared by sources of different data type: `name,` `provider,` `data_type`, etc. 
Specific features could be represented in smaller tables, eg. a `static_reference` table with the columns `realtime_source_id` and `static_reference_id`.
Since we are not expecting a big quantity (>100k sources), it shouldn't be an issue in terms of storage and memory.
